services:

    proxy:
        image: nginx
        ports:
            - '1883:1883'
            - '8080:8080'
            - '8443:8443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

    postgres:
        image: postgres:18
        environment:
            POSTGRES_PASSWORD: secret
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/18/docker
            # - ./initdb.d:/docker-entrypoint-initdb.d

    migrate-postgres:
        image: flyway/flyway:12-alpine
        command: migrate
        volumes:
            - ./migrations/postgres/flyway.conf:/flyway/conf/flyway.conf
            - ./migrations/postgresql:/flyway/sql

    migrate-sqlite:
        image: flyway/flyway:12-alpine
        command: migrate
        volumes:
            - ./migrations/sqlite/flyway.conf:/flyway/conf/flyway.conf
            - ./migrations/sqlite:/flyway/sql
            - ./src/Host/:/host

    silo1:
        build: .
        environment:
            ASPNETCORE_URLS: http://+:8080
            Orleans_UseClustering: ado
            Orleans__Invariant: Npgsql
            Orleans__ConnectionString: "Host=postgres;Database=demo;Username=postgres;Password=secret"
        ports:
            - '8081:8080'

    silo2:
        build: .
        environment:
            ASPNETCORE_URLS: http://+:8080
            Orleans_UseClustering: ado
            Orleans__Invariant: Npgsql
            Orleans__ConnectionString: "Host=postgres;Database=demo;Username=postgres;Password=secret"
        ports:
            - '8082:8080'


    silo3:
        build: .
        environment:
            ASPNETCORE_URLS: http://+:8080
            Orleans_UseClustering: ado
            Orleans__Invariant: Npgsql
            Orleans__ConnectionString: "Host=postgres;Database=demo;Username=postgres;Password=secret"
        ports:
            - '8083:8080'

volumes:
    pgdata: